spring:
  data:
    mongodb:
      host: ds117806.mlab.com:17806
      username: CloudFoundry_r9qmnb3b_5pf04554_918dhkib
      password: QJGpftxUK44M4BmwaVD8zDXuZ9mxpCWE
      database: CloudFoundry_r9qmnb3b_5pf04554
  rabbitmq:
    host: hornet.rmq.cloudamqp.com/vfxujshy
    username: vfxujshy
    password: k1qb0RyLTPgRBK9Crh4dDRyD6LdDL1C_
axon:
  events:
    database: CloudFoundry_r9qmnb3b_5pf04554
server:
  port: 8093
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG