axon:
  events:
    database: operation-event-store
    snapshot-limit: 1000
    default-exchange: operation-exchange
    projection-event-queue: projection-event-queue
    projection-cmd-queue: projection-cmd-queue
    default-event-routing-key: event
    default-cmd-routing-key: cmd
    class-path-package: com.ia
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: operation-cmd
  data:
    mongodb:
      database: operation-view-store

server:
  port: 8093
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG