spring:
  data:
    mongodb:
      host: ds115701.mlab.com:15701
      username: operation
      password: operation1.0
      database: CloudFoundry_ho0n441m_2q86qa89
  rabbitmq:
    host: zebra.rmq.cloudamqp.com/reztdanr
    username: reztdanr
    password: VsJv1qQPXw-AWKmeeWnw8-zUezVKMFIl
axon:
  events:
    database: CloudFoundry_ho0n441m_2q86qa89
server:
  port: 8093
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG